package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Footprint;
import org.linlinjava.litemall.db.domain.FootprintExample;

public interface FootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    long countByExample(FootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    int deleteByExample(FootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    int insert(Footprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    int insertSelective(Footprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    Footprint selectOneByExample(FootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    Footprint selectOneByExampleSelective(@Param("example") FootprintExample example, @Param("selective") Footprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    List<Footprint> selectByExampleSelective(@Param("example") FootprintExample example, @Param("selective") Footprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    List<Footprint> selectByExample(FootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    Footprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Footprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    Footprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    Footprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Footprint record, @Param("example") FootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Footprint record, @Param("example") FootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Footprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Footprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") FootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}