package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.HouseAttribute;
import org.linlinjava.litemall.db.domain.HouseAttributeExample;

public interface HouseAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    long countByExample(HouseAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(HouseAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    int insert(HouseAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    int insertSelective(HouseAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    HouseAttribute selectOneByExample(HouseAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    HouseAttribute selectOneByExampleSelective(@Param("example") HouseAttributeExample example, @Param("selective") HouseAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    List<HouseAttribute> selectByExampleSelective(@Param("example") HouseAttributeExample example, @Param("selective") HouseAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    List<HouseAttribute> selectByExample(HouseAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    HouseAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") HouseAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    HouseAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    HouseAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HouseAttribute record, @Param("example") HouseAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HouseAttribute record, @Param("example") HouseAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HouseAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HouseAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") HouseAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}