package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.NoticeAdmin;
import org.linlinjava.litemall.db.domain.NoticeAdminExample;

public interface NoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    long countByExample(NoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    int deleteByExample(NoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    int insert(NoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    int insertSelective(NoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    NoticeAdmin selectOneByExample(NoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    NoticeAdmin selectOneByExampleSelective(@Param("example") NoticeAdminExample example, @Param("selective") NoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    List<NoticeAdmin> selectByExampleSelective(@Param("example") NoticeAdminExample example, @Param("selective") NoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    List<NoticeAdmin> selectByExample(NoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    NoticeAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") NoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    NoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    NoticeAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NoticeAdmin record, @Param("example") NoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NoticeAdmin record, @Param("example") NoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") NoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}