package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.System;
import org.linlinjava.litemall.db.domain.SystemExample;

public interface SystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    long countByExample(SystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    int deleteByExample(SystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    int insert(System record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    int insertSelective(System record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    System selectOneByExample(SystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    System selectOneByExampleSelective(@Param("example") SystemExample example, @Param("selective") System.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    List<System> selectByExampleSelective(@Param("example") SystemExample example, @Param("selective") System.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    List<System> selectByExample(SystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    System selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") System.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    System selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    System selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") System record, @Param("example") SystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") System record, @Param("example") SystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(System record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(System record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}