package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class Contract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contract
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contract
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_sn
     *
     * @mbg.generated
     */
    private String contractSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.user_id1
     *
     * @mbg.generated
     */
    private Integer userId1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.user_id2
     *
     * @mbg.generated
     */
    private Integer userId2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_status
     *
     * @mbg.generated
     */
    private Short contractStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.name1
     *
     * @mbg.generated
     */
    private String name1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.name2
     *
     * @mbg.generated
     */
    private String name2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.idcard1
     *
     * @mbg.generated
     */
    private String idcard1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.idcard2
     *
     * @mbg.generated
     */
    private String idcard2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.block_id
     *
     * @mbg.generated
     */
    private String blockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.hash
     *
     * @mbg.generated
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.start_time
     *
     * @mbg.generated
     */
    private LocalDateTime startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.address_detail
     *
     * @mbg.generated
     */
    private String addressDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.county
     *
     * @mbg.generated
     */
    private String county;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.id
     *
     * @return the value of contract.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.id
     *
     * @param id the value for contract.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_sn
     *
     * @return the value of contract.contract_sn
     *
     * @mbg.generated
     */
    public String getContractSn() {
        return contractSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_sn
     *
     * @param contractSn the value for contract.contract_sn
     *
     * @mbg.generated
     */
    public void setContractSn(String contractSn) {
        this.contractSn = contractSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.user_id1
     *
     * @return the value of contract.user_id1
     *
     * @mbg.generated
     */
    public Integer getUserId1() {
        return userId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.user_id1
     *
     * @param userId1 the value for contract.user_id1
     *
     * @mbg.generated
     */
    public void setUserId1(Integer userId1) {
        this.userId1 = userId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.user_id2
     *
     * @return the value of contract.user_id2
     *
     * @mbg.generated
     */
    public Integer getUserId2() {
        return userId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.user_id2
     *
     * @param userId2 the value for contract.user_id2
     *
     * @mbg.generated
     */
    public void setUserId2(Integer userId2) {
        this.userId2 = userId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_status
     *
     * @return the value of contract.contract_status
     *
     * @mbg.generated
     */
    public Short getContractStatus() {
        return contractStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_status
     *
     * @param contractStatus the value for contract.contract_status
     *
     * @mbg.generated
     */
    public void setContractStatus(Short contractStatus) {
        this.contractStatus = contractStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.name1
     *
     * @return the value of contract.name1
     *
     * @mbg.generated
     */
    public String getName1() {
        return name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.name1
     *
     * @param name1 the value for contract.name1
     *
     * @mbg.generated
     */
    public void setName1(String name1) {
        this.name1 = name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.name2
     *
     * @return the value of contract.name2
     *
     * @mbg.generated
     */
    public String getName2() {
        return name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.name2
     *
     * @param name2 the value for contract.name2
     *
     * @mbg.generated
     */
    public void setName2(String name2) {
        this.name2 = name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.idcard1
     *
     * @return the value of contract.idcard1
     *
     * @mbg.generated
     */
    public String getIdcard1() {
        return idcard1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.idcard1
     *
     * @param idcard1 the value for contract.idcard1
     *
     * @mbg.generated
     */
    public void setIdcard1(String idcard1) {
        this.idcard1 = idcard1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.idcard2
     *
     * @return the value of contract.idcard2
     *
     * @mbg.generated
     */
    public String getIdcard2() {
        return idcard2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.idcard2
     *
     * @param idcard2 the value for contract.idcard2
     *
     * @mbg.generated
     */
    public void setIdcard2(String idcard2) {
        this.idcard2 = idcard2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.price
     *
     * @return the value of contract.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.price
     *
     * @param price the value for contract.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.block_id
     *
     * @return the value of contract.block_id
     *
     * @mbg.generated
     */
    public String getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.block_id
     *
     * @param blockId the value for contract.block_id
     *
     * @mbg.generated
     */
    public void setBlockId(String blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.hash
     *
     * @return the value of contract.hash
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.hash
     *
     * @param hash the value for contract.hash
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.start_time
     *
     * @return the value of contract.start_time
     *
     * @mbg.generated
     */
    public LocalDateTime getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.start_time
     *
     * @param startTime the value for contract.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.end_time
     *
     * @return the value of contract.end_time
     *
     * @mbg.generated
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.end_time
     *
     * @param endTime the value for contract.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.add_time
     *
     * @return the value of contract.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.add_time
     *
     * @param addTime the value for contract.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.deleted
     *
     * @return the value of contract.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.deleted
     *
     * @param deleted the value for contract.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.update_time
     *
     * @return the value of contract.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.update_time
     *
     * @param updateTime the value for contract.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.province
     *
     * @return the value of contract.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.province
     *
     * @param province the value for contract.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.city
     *
     * @return the value of contract.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.city
     *
     * @param city the value for contract.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.address_detail
     *
     * @return the value of contract.address_detail
     *
     * @mbg.generated
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.address_detail
     *
     * @param addressDetail the value for contract.address_detail
     *
     * @mbg.generated
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.county
     *
     * @return the value of contract.county
     *
     * @mbg.generated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.county
     *
     * @param county the value for contract.county
     *
     * @mbg.generated
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", contractSn=").append(contractSn);
        sb.append(", userId1=").append(userId1);
        sb.append(", userId2=").append(userId2);
        sb.append(", contractStatus=").append(contractStatus);
        sb.append(", name1=").append(name1);
        sb.append(", name2=").append(name2);
        sb.append(", idcard1=").append(idcard1);
        sb.append(", idcard2=").append(idcard2);
        sb.append(", price=").append(price);
        sb.append(", blockId=").append(blockId);
        sb.append(", hash=").append(hash);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", addTime=").append(addTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", addressDetail=").append(addressDetail);
        sb.append(", county=").append(county);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Contract other = (Contract) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getContractSn() == null ? other.getContractSn() == null : this.getContractSn().equals(other.getContractSn()))
            && (this.getUserId1() == null ? other.getUserId1() == null : this.getUserId1().equals(other.getUserId1()))
            && (this.getUserId2() == null ? other.getUserId2() == null : this.getUserId2().equals(other.getUserId2()))
            && (this.getContractStatus() == null ? other.getContractStatus() == null : this.getContractStatus().equals(other.getContractStatus()))
            && (this.getName1() == null ? other.getName1() == null : this.getName1().equals(other.getName1()))
            && (this.getName2() == null ? other.getName2() == null : this.getName2().equals(other.getName2()))
            && (this.getIdcard1() == null ? other.getIdcard1() == null : this.getIdcard1().equals(other.getIdcard1()))
            && (this.getIdcard2() == null ? other.getIdcard2() == null : this.getIdcard2().equals(other.getIdcard2()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getBlockId() == null ? other.getBlockId() == null : this.getBlockId().equals(other.getBlockId()))
            && (this.getHash() == null ? other.getHash() == null : this.getHash().equals(other.getHash()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getAddressDetail() == null ? other.getAddressDetail() == null : this.getAddressDetail().equals(other.getAddressDetail()))
            && (this.getCounty() == null ? other.getCounty() == null : this.getCounty().equals(other.getCounty()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getContractSn() == null) ? 0 : getContractSn().hashCode());
        result = prime * result + ((getUserId1() == null) ? 0 : getUserId1().hashCode());
        result = prime * result + ((getUserId2() == null) ? 0 : getUserId2().hashCode());
        result = prime * result + ((getContractStatus() == null) ? 0 : getContractStatus().hashCode());
        result = prime * result + ((getName1() == null) ? 0 : getName1().hashCode());
        result = prime * result + ((getName2() == null) ? 0 : getName2().hashCode());
        result = prime * result + ((getIdcard1() == null) ? 0 : getIdcard1().hashCode());
        result = prime * result + ((getIdcard2() == null) ? 0 : getIdcard2().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getBlockId() == null) ? 0 : getBlockId().hashCode());
        result = prime * result + ((getHash() == null) ? 0 : getHash().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getAddressDetail() == null) ? 0 : getAddressDetail().hashCode());
        result = prime * result + ((getCounty() == null) ? 0 : getCounty().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table contract
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table contract
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table contract
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table contract
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        contractSn("contract_sn", "contractSn", "VARCHAR", false),
        userId1("user_id1", "userId1", "INTEGER", false),
        userId2("user_id2", "userId2", "INTEGER", false),
        contractStatus("contract_status", "contractStatus", "SMALLINT", false),
        name1("name1", "name1", "VARCHAR", false),
        name2("name2", "name2", "VARCHAR", false),
        idcard1("idcard1", "idcard1", "VARCHAR", false),
        idcard2("idcard2", "idcard2", "VARCHAR", false),
        price("price", "price", "DECIMAL", false),
        blockId("block_id", "blockId", "VARCHAR", false),
        hash("hash", "hash", "VARCHAR", false),
        startTime("start_time", "startTime", "TIMESTAMP", false),
        endTime("end_time", "endTime", "TIMESTAMP", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        province("province", "province", "VARCHAR", false),
        city("city", "city", "VARCHAR", false),
        addressDetail("address_detail", "addressDetail", "VARCHAR", false),
        county("county", "county", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table contract
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table contract
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table contract
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table contract
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table contract
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table contract
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table contract
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}